name: Build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest-m
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'corretto'
      - uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: 8.6
      - name: Clean Gradle cache
        run: rm -rf ~/.gradle/caches/
      - name: Clean up resources
        run: |
          fuser -k 11001/tcp || true
          fuser -k 11002/tcp || true
          fuser -k 11003/tcp || true
          fuser -k 11004/tcp || true
          fuser -k 11005/tcp || true
      - name: Build with Gradle
        run: ./gradlew build --no-daemon
